# Generated by Django 4.1.3 on 2022-12-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounterOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.CharField(max_length=120)),
                ('comment', models.CharField(max_length=300)),
                ('amount', models.FloatField()),
                ('equity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrepreneur', models.CharField(max_length=120)),
                ('pitchTitle', models.CharField(max_length=120)),
                ('pitchIdea', models.CharField(max_length=300)),
                ('askAmount', models.FloatField()),
                ('equity', models.FloatField()),
                ('offers', models.ManyToManyField(blank=True, to='myapi.counteroffer')),
            ],
        ),
    ]
